# -*- coding: utf-8 -*-
"""fibonacciseries.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXEcSCNx3PTJFgu0qqEk9IwdMhX1kVCn
"""

def fibo(n):
    a,b=0,1
    print(a,b,end=' ')
    for i in range(n-2):
        c=a+b
        print(c,end=' ')
        a,b=b,c
n=int(input('enter number of elements:'))
fibo(n)

