# -*- coding: utf-8 -*-
"""hello world

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e5J-KrAMvhAlZnoUcUM-7dYtVLQu00UB
"""

print('hello world')