# -*- coding: utf-8 -*-
"""set_opeartion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_LKHNRiCkSPvUpbKOe3RgB4Zsa0zaAW
"""

s1={5,6,7,8,9}
s2={2,5,6,3,8}
print('union of s1 and s2=',s1|s2)
print('Intersection of s1 and s2=',s1&s2)
print('Difference between s1 and s2=',s1-s2)
print('Symmetric difference of s1 and s2=',s1^s2)

